//% weight=67 color=#5C406C icon="\uf0a3"
namespace Lantern3D {

    //% block
    export function raycastLantern(): void {
        Render.setViewMode(ViewMode.raycastingView)
        let mySprite2 = sprites.create(img`
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbb...................bbbbbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbb.........................bbbbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbb...............................bbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbbb.....................................bbbbbbbbbbccccccfffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb.........................................bbbbbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb...........................................bbbbbbbbbccccccfffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb...............................................bbbbbbbbccccccffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb.................................................bbbbbbbbccccccfffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.....................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.......................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.........................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb...........................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.............................................................bbbbbbcccccffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffcccccbbbbbbbb...............................................................bbbbbbcccccfffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.................................................................bbbbbbcccccffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffcccccbbbbbbbb...................................................................bbbbbbcccccfffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffccccbbbbbbbb.....................................................................bbbbbbccccfffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffcccccbbbbbbb.......................................................................bbbbbcccccffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffccccbbbbbbbb.......................................................................bbbbbbccccffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................................bbbbbcccccfffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccfffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccfffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccfffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccfffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccfffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccfffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffcccccbbbbbb.................................................................................bbbbcccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbbb.................................................................................bbbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffcccccbbbbb...................................................................................bbbcccccffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccfffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccfffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccfffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccfffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccfffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccfffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffcccccbbbbbb...........................................................................bbbbcccccfffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffccccbbbbbb...........................................................................bbbbccccffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffcccccbbbbbb.........................................................................bbbbcccccffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffccccbbbbbbb.......................................................................bbbbbccccfffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffcccccbbbbbb.......................................................................bbbbcccccfffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffcccccbbbbbb.....................................................................bbbbcccccffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffcccccbbbbbb...................................................................bbbbcccccfffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffcccccbbbbbb.................................................................bbbbcccccffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...............................................................bbbbbcccccffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.............................................................bbbbbcccccfffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...........................................................bbbbbcccccffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................bbbbbcccccfffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.......................................................bbbbbccccccfffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.....................................................bbbbbccccccffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb.................................................bbbbbbccccccfffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb...............................................bbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbb...........................................bbbbbbbccccccfffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbb.........................................bbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbb.....................................bbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbb...............................bbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbb.........................bbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbb...................bbbbbbbbbbbccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        `, SpriteKind.Player)
        mySprite2.setFlag(SpriteFlag.RelativeToCamera, true)
        mySprite2,
            [img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbb...................bbbbbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbb.........................bbbbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbb...............................bbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbbb.....................................bbbbbbbbbbccccccffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb.........................................bbbbbbbbbccccccfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb...........................................bbbbbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb...............................................bbbbbbbbccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb.................................................bbbbbbbbccccccffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.....................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.......................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.........................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb...........................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.............................................................bbbbbbcccccfffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcccccbbbbbbbb...............................................................bbbbbbcccccffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.................................................................bbbbbbcccccfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffcccccbbbbbbbb...................................................................bbbbbbcccccffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbbbb.....................................................................bbbbbbccccffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffcccccbbbbbbb.......................................................................bbbbbcccccfffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbbbb.......................................................................bbbbbbccccfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................................bbbbbcccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffcccccbbbbbb.................................................................................bbbbcccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbbb.................................................................................bbbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffcccccbbbbb...................................................................................bbbcccccfffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffcccccbbbbbb...........................................................................bbbbcccccffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbb...........................................................................bbbbccccfffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffcccccbbbbbb.........................................................................bbbbcccccfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbbb.......................................................................bbbbbccccffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffcccccbbbbbb.......................................................................bbbbcccccffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbb.....................................................................bbbbcccccfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcccccbbbbbb...................................................................bbbbcccccffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbb.................................................................bbbbcccccfffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...............................................................bbbbbcccccfffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.............................................................bbbbbcccccffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...........................................................bbbbbcccccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................bbbbbcccccffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.......................................................bbbbbccccccffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.....................................................bbbbbccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb.................................................bbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb...............................................bbbbbbccccccfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbb...........................................bbbbbbbccccccffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbb.........................................bbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbb.....................................bbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbb...............................bbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbb.........................bbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbb...................bbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `, img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbb...................bbbbbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbb.........................bbbbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbb...............................bbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbbb.....................................bbbbbbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb.........................................bbbbbbbbbccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb...........................................bbbbbbbbbccccccffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb...............................................bbbbbbbbccccccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb.................................................bbbbbbbbccccccffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.....................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.......................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.........................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb...........................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.............................................................bbbbbbcccccfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccbbbbbbbb...............................................................bbbbbbcccccffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.................................................................bbbbbbcccccfffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcccccbbbbbbbb...................................................................bbbbbbcccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffccccbbbbbbbb.....................................................................bbbbbbccccffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbbb.......................................................................bbbbbcccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffccccbbbbbbbb.......................................................................bbbbbbccccfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................................bbbbbcccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccfffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcccccbbbbbb.................................................................................bbbbcccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbbb.................................................................................bbbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcccccbbbbb...................................................................................bbbcccccfffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccfffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffcccccbbbbbb...........................................................................bbbbcccccffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffccccbbbbbb...........................................................................bbbbccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbb.........................................................................bbbbcccccfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffccccbbbbbbb.......................................................................bbbbbccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcccccbbbbbb.......................................................................bbbbcccccffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbb.....................................................................bbbbcccccfffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccbbbbbb...................................................................bbbbcccccffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbb.................................................................bbbbcccccfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...............................................................bbbbbcccccfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.............................................................bbbbbcccccffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...........................................................bbbbbcccccfffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................bbbbbcccccffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.......................................................bbbbbccccccffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.....................................................bbbbbccccccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb.................................................bbbbbbccccccffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb...............................................bbbbbbccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbb...........................................bbbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbb.........................................bbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbb.....................................bbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbb...............................bbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbb.........................bbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbb...................bbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `, img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbbb...................bbbbbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbbbb.........................bbbbbbbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbbb...............................bbbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbbb.....................................bbbbbbbbbbccccccffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb.........................................bbbbbbbbbccccccfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbbb...........................................bbbbbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb...............................................bbbbbbbbccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbbb.................................................bbbbbbbbccccccffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.....................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.......................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb.........................................................bbbbbbbcccccffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbbbb...........................................................bbbbbbbcccccfffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.............................................................bbbbbbcccccfffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcccccbbbbbbbb...............................................................bbbbbbcccccffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbbbb.................................................................bbbbbbcccccfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffcccccbbbbbbbb...................................................................bbbbbbcccccffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbbbb.....................................................................bbbbbbccccffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffcccccbbbbbbb.......................................................................bbbbbcccccfffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbbbb.......................................................................bbbbbbccccfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................................bbbbbcccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbbb...........................................................................bbbbbccccffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbbb.............................................................................bbbbbccccfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbbb...............................................................................bbbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffcccccbbbbbb.................................................................................bbbbcccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbbb.................................................................................bbbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffccccbbbbbb...................................................................................bbbbccccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffcccccbbbbb...................................................................................bbbcccccfffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffccccbbbbbb.................................................................................bbbbccccffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffcccccbbbbbb...............................................................................bbbbcccccffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffccccbbbbbb...............................................................................bbbbccccfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcccccbbbbbb.............................................................................bbbbcccccfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffccccbbbbbb.............................................................................bbbbccccffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffcccccbbbbbb...........................................................................bbbbcccccffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffccccbbbbbb...........................................................................bbbbccccfffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffcccccbbbbbb.........................................................................bbbbcccccfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffccccbbbbbbb.......................................................................bbbbbccccffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffcccccbbbbbb.......................................................................bbbbcccccffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbb.....................................................................bbbbcccccfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcccccbbbbbbb...................................................................bbbbbcccccfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcccccbbbbbb...................................................................bbbbcccccffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbb.................................................................bbbbcccccfffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...............................................................bbbbbcccccfffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.............................................................bbbbbcccccffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb...........................................................bbbbbcccccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcccccbbbbbbb.........................................................bbbbbcccccffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.......................................................bbbbbccccccffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbb.....................................................bbbbbccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb.................................................bbbbbbccccccffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbb...............................................bbbbbbccccccfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccccccbbbbbbbbb...........................................bbbbbbbccccccffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbb.........................................bbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbb.....................................bbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbb...............................bbbbbbbbcccccccffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffcccccccbbbbbbbbbbbb.........................bbbbbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbb...................bbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `],
            100,
            true

    }
}
